import {Timestamp} from 'firebase/firestore';
import {CoreInputType, CoreUnitType} from '@/types/core-metric';
import {MetricDefinition} from '@/types/formdefinition';

const now: Timestamp = Timestamp.now();

export const staticNutritionPackMDs: MetricDefinition[] = [
    // Chunk 1: Caffeine, Calories, and Macronutrients
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "caffeine_consumption",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.MILLIGRAM, // caffeine typically in mg
        metricTitle: "Caffeine Consumption",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "calories",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.KCAL,
        metricTitle: "Calories",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "total_fat",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.GRAM,
        metricTitle: "Total Fat",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "saturated_fat",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.GRAM,
        metricTitle: "Saturated Fat",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "trans_fat",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.GRAM,
        metricTitle: "Trans Fat",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "polyunsaturated_fat",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.GRAM,
        metricTitle: "Polyunsaturated Fat",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "monounsaturated_fat",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.GRAM,
        metricTitle: "Monounsaturated Fat",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "cholesterol",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.MILLIGRAM,
        metricTitle: "Cholesterol",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "sodium",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.MILLIGRAM,
        metricTitle: "Sodium",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "total_carbohydrates",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.GRAM,
        metricTitle: "Total Carbohydrates",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "dietary_fiber",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.GRAM,
        metricTitle: "Dietary Fiber",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },

    // Chunk 2: Sugars and Protein
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "sugars",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.GRAM,
        metricTitle: "Sugars",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "added_sugars",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.GRAM,
        metricTitle: "Added Sugars",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "protein",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.GRAM,
        metricTitle: "Protein",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },

    // Chunk 3: Vitamins & B-Complex Nutrients
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "vitamin_a",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.MICROGRAM, // using micrograms per nutrition labels
        metricTitle: "Vitamin A",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "vitamin_c",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.MILLIGRAM,
        metricTitle: "Vitamin C",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "vitamin_d",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.MICROGRAM, // using micrograms
        metricTitle: "Vitamin D",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "vitamin_e",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.MICROGRAM, // using micrograms
        metricTitle: "Vitamin E",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "vitamin_k",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.MICROGRAM, // using micrograms
        metricTitle: "Vitamin K",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "thiamin_vitamin_b1",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.MILLIGRAM,
        metricTitle: "Thiamin (Vitamin B1)",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "riboflavin_vitamin_b2",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.MILLIGRAM,
        metricTitle: "Riboflavin (Vitamin B2)",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "niacin_vitamin_b3",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.MILLIGRAM,
        metricTitle: "Niacin (Vitamin B3)",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "vitamin_b6",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.MILLIGRAM,
        metricTitle: "Vitamin B6",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "folate_vitamin_b9",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.MICROGRAM,
        metricTitle: "Folate (Vitamin B9)",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "vitamin_b12",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.MICROGRAM,
        metricTitle: "Vitamin B12",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "pantothenic_acid_vitamin_b5",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.MILLIGRAM,
        metricTitle: "Pantothenic Acid (Vitamin B5)",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "biotin_vitamin_b7",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.MICROGRAM,
        metricTitle: "Biotin (Vitamin B7)",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },

    // Chunk 4: Minerals, Fatty Acids, and Others
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "calcium",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.MILLIGRAM,
        metricTitle: "Calcium",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "iron",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.MILLIGRAM,
        metricTitle: "Iron",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "magnesium",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.MILLIGRAM,
        metricTitle: "Magnesium",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "phosphorus",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.MILLIGRAM,
        metricTitle: "Phosphorus",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "potassium",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.MILLIGRAM,
        metricTitle: "Potassium",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "zinc",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.MILLIGRAM,
        metricTitle: "Zinc",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "selenium",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.MICROGRAM,
        metricTitle: "Selenium",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "copper",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.MILLIGRAM,
        metricTitle: "Copper",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "manganese",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.MILLIGRAM,
        metricTitle: "Manganese",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "fluoride",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.MILLIGRAM,
        metricTitle: "Fluoride",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "omega_3_fatty_acids",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.GRAM,
        metricTitle: "Omega-3 Fatty Acids",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "omega_6_fatty_acids",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.GRAM,
        metricTitle: "Omega-6 Fatty Acids",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "choline",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.MILLIGRAM,
        metricTitle: "Choline",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
    {
        id: "",
        formDefinitionId: "",
        coreMetricId: "iodine",
        inputType: CoreInputType.NUMBER,
        unitType: CoreUnitType.MICROGRAM,
        metricTitle: "Iodine",
        createdAt: now,
        updatedAt: null,
        deletedAt: null,
    },
];